name: Grover_Automation

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up jdk 11
      run: actions/setup-java@v1
      with:
       java-version: 11
       
    name: build with maven
    run: mvn test
