name: Grover_Automation

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up jdk 11
      uses: actions/setup-java@v1
      with:
       java-version: 11
       
    - name: run core
      run: cd core && mvn clean && mvn install
      
    - name: run UI test
      run: cd GroverUITest &&  mvn clean && mvn install
       
  
      
      
